---
title: "Palmer Penguins"
subtitle: "TidyTuesday 2020, Week 31"
author: "Botan Ağın"
date: "11/30/2020"
output: html_document
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(palmerpenguins)
library(ggridges)
library(showtext)
library(magick)
library(here)
```

```{r fonts}
font_add_google("Lobster")
font_add_google("Dancing Script")
showtext_auto()
```

```{r wrangle}
penguins_long <- penguins %>% 
  pivot_longer(
    bill_length_mm:body_mass_g, 
    names_to = "attribute", 
    values_to = "value"
  ) %>% 
  mutate(
    attribute = attribute %>% 
      str_replace_all("_", " ") %>% 
      str_to_title() %>% 
      str_replace("Mm$", "(mm)") %>% 
      str_replace("G$", "(g)"),
    sex = str_to_title(sex)
  ) %>% 
  mutate_if(is.character, as.factor) %>% 
  drop_na()
```

```{r images}
pengs <- image_read(here("images", "penguin-species.png"))
bill <- image_read(here("images", "culmen-depth.png"))
```

```{r plot}
png(here("plots", "2020-w31-palmerpenguins.png"), 
    width = 6, height = 9, units = "in", res = 300)

penguins_long %>% 
  ggplot(aes(value, species, fill = species, color = species)) +
  geom_density_ridges(alpha = 0.75) + 
  labs(
    title = "\n Palmer Penguins",
    subtitle = "Distrubutions of Attributes 
    by Species \n",
    caption = "\n \n \n
      Data: github.com/allisonhorst/palmerpenguins
      Source: Gorman, Williams & Fraser (2014)
      Artwork by @allison_horst
      Visualization by @botanagin"
  ) + 
  theme_minimal() + 
  theme(
    axis.title = element_blank(),
    axis.text = element_text(size = 10),
    axis.text.x = element_text(family = "Dancing Script"),
    axis.text.y = element_blank(),
    strip.text = element_text(family = "Lobster", 
                              size = 12,
                              face = "bold",
                              color = "gray30"),
    panel.grid = element_blank(),
    legend.position = "none",
    plot.background = element_rect(fill = "snow"),
    plot.title = element_text(hjust = 0.1,
                              family = "Lobster",
                              face = "bold",
                              size = 24),
    plot.subtitle = element_text(hjust = 0.1, 
                                 family = "Lobster",
                                 face = "bold",
                                 color = "gray40",
                                 size = 18),
    plot.caption = element_text(hjust = 1, 
                                family = "Dancing Script", 
                                size = 12),
    plot.margin = margin(15, 15, 15, 15, unit = "pt")
  ) +
  scale_fill_manual(values = c("darkorange", "darkorchid", "darkcyan")) + 
  scale_color_manual(values = c("darkorange", "darkorchid", "darkcyan")) +
  facet_wrap(~ attribute, scales = "free", ncol = 1) 
grid::grid.raster(bill, width = 0.33, height = 0.17, x = 0.77, y = 0.88)
grid::grid.raster(pengs, width = 0.33, height = 0.17, x = 0.25, y = 0.1)

dev.off()
```